create table if not exists T_BUSLINIE (
    BUSLINIE_ID int NOT NULL AUTO_INCREMENT,
    BUSLINIE_NAME varchar(100) UNIQUE,
    PRIMARY KEY (BUSLINIE_ID)
);

create table if not exists T_HALTESTELLE (
    HALTESTELLE_ID int NOT NULL AUTO_INCREMENT,
    HALTESTELLE_NAME varchar(100) UNIQUE,
    PRIMARY KEY (HALTESTELLE_ID)
);

create table if not exists T_BUSFAHRT (
    BUSFAHRT_ID integer NOT NULL AUTO_INCREMENT,
    BUSLINIE_ID integer NOT NULL ,
    START_HALTESTELLE_ID integer NOT NULL ,
    ZIEL_HALTESTELLE_ID integer NOT NULL ,
    ABFAHRTS_ZEIT DATETIME not null,
    ANKUNFTS_ZEIT DATETIME not null,
    PRIMARY KEY (BUSFAHRT_ID),
    foreign key (BUSLINIE_ID) references T_BUSLINIE(BUSLINIE_ID),
    foreign key (START_HALTESTELLE_ID) references T_HALTESTELLE(HALTESTELLE_ID),
    foreign key (ZIEL_HALTESTELLE_ID) references T_HALTESTELLE(HALTESTELLE_ID)
);
create table if not exists T_FAHRPLAN (
    FAHRPLAN_ID int NOT NULL,
    BUSLINIE_ID int NOT NULL,
    foreign key (BUSLINIE_ID) references T_BUSLINIE(BUSLINIE_ID),
    CONSTRAINT PK_FAHRPLAN PRIMARY KEY (FAHRPLAN_ID, BUSLINIE_ID)
);

ALTER IGNORE TABLE T_BUSFAHRT ADD UNIQUE INDEX (BUSLINIE_ID, START_HALTESTELLE_ID, ZIEL_HALTESTELLE_ID,ANKUNFTS_ZEIT, ABFAHRTS_ZEIT);


