
create table if not exists T_BUSLINIE (
    NAME varchar(100) UNIQUE,
    PRIMARY KEY (NAME)
);

create table if not exists T_HALTESTELLE (
    NAME varchar(100) UNIQUE,
    PRIMARY KEY (NAME)
);

create table if not exists T_BUSFAHRT (
    id integer NOT NULL AUTO_INCREMENT,
    BUSLINIE_NAME varchar(100) UNIQUE,
    START_HALTESTELLE_NAME varchar(100) UNIQUE,
    ZIEL_HALTESTELLE_NAME varchar(100) UNIQUE,
    ABFAHRTS_ZEIT DATETIME not null,
    ANKUNFTS_ZEIT DATETIME not null,
    PRIMARY KEY (id),
    FOREIGN KEY (BUSLINIE_NAME) REFERENCES T_BUSLINIE(NAME),
    FOREIGN KEY (START_HALTESTELLE_NAME) REFERENCES T_HALTESTELLE(NAME),
    FOREIGN KEY (ZIEL_HALTESTELLE_NAME) REFERENCES T_HALTESTELLE(NAME)

);

