
create table T_BUSLINIE (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    NAME varchar(100)
);

create table T_BUSFAHRT (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    BUSLINIE_ID integer not null,
    START_HALTESTELLE_ID integer not null,
    ZIEL_HALTESTELLE_ID integer not null,
    ABFAHRTS_ZEIT DATETIME not null,
    ANKUNFTS_ZEIT DATETIME not null
);

create table T_HALTESTELLE (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    NAME varchar(100)
);

alter table T_BUSFAHRT add foreign key (BUSLINIE_ID) references T_BUSLINIE(id);
alter table T_BUSFAHRT add foreign key (START_HALTESTELLE_ID) references T_HALTESTELLE(id);
alter table T_BUSFAHRT add foreign key (ZIEL_HALTESTELLE_ID) references T_HALTESTELLE(id);
